In [8]:
import numpy as np
#np.argmax(np.bincount([0, 4, 1], weights=[0.2, 0.2, 0.6]))
np.argmax([10, 0, 1, 1 ,5])


0

In [12]:
ex = np.array([[0.9, 0.1], [0.8, 1.2], [4.4, 6.6]])
np.argmax(ex)

5

In [13]:
print(ex)

[[0.9 0.1]
 [0.8 1.2]
 [4.4 6.6]]


In [18]:
np.bincount([0, 4, 1, 5, 5])

array([1, 1, 0, 0, 1, 2])

In [19]:
np.bincount([0, 4, 1], weights=[0.2, 0.2, 0.6])

array([0.2, 0.6, 0. , 0. , 0.2])

In [22]:
np.bincount([0, 4, 1, 5, 5], weights= [1, 1, 1, 1, 1])

array([1., 1., 0., 0., 1., 2.])

In [23]:
np.bincount([0, 4, 1, 5, 5], weights= [2, 2, 2, 2, 2])

array([2., 2., 0., 0., 2., 4.])

In [26]:
np.bincount([0, 4, 1, 5, 10], weights= [1, 1, 1, 1, 1])

array([1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1.])

In [28]:
np.bincount([0, 4, 2.5, 5, 10], weights= [1, 1, 1, 1, 1])

array([1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1.])

In [29]:
np.bincount([0, 4, 2.5, 5, 10.5], weights= [1, 1, 1, 1, 1])

array([1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1.])

In [30]:
np.bincount([0, 4, 2.5, 5, 10])

array([1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1])

In [32]:
np.bincount([0, 4, 2.5, 5, 10.5])

array([1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1])

In [34]:
np.bincount([1,1,4], weights=[1,1,2])

array([0., 2., 0., 0., 2.])

In [35]:
np.bincount([1,1,4], weights=[1,1,0.5])

array([0. , 2. , 0. , 0. , 0.5])

In [36]:
np.bincount([1, 2, 5, 6, 2, 1, 8, 8, 8], weights = [1, 1, 1, 0.5, 1, 1, 1, 1, 2])

array([0. , 2. , 2. , 0. , 0. , 1. , 0.5, 0. , 4. ])

In [37]:
import numpy as np
l = np.array([1, 2, 1, 4, 1])
ll = np.random.choice(l, size=l.shape, replace=False)
print(ll)

[1 1 4 2 1]


In [46]:
import numpy as np
l = np.array([1, 2, 1, 4, 1])
ll = np.random.choice(l, size=4, replace=False)
print(ll)

[2 4 1 1]


In [47]:
import numpy as np
l = np.array([1, 2, 1, 4, 1])
ll = np.random.choice(l, size=3, replace=False)
print(ll)

[2 1 4]


In [48]:
from sklearn.datasets import load_iris
from sklearn import tree
iris = load_iris()
clf = tree.DecisionTreeClassifier()
clf = clf.fit(iris.data, iris.target) # iris.data == features, iris.target == labels. fit() ajusta o modelo.
import graphviz
dot_data = tree.export_graphviz(clf, out_file=None)
graph = graphviz.Source(dot_data)
graph.render("iris")

'iris.pdf'

In [54]:
from sklearn.datasets import load_iris
from sklearn import tree
iris = load_iris()
clf = tree.DecisionTreeClassifier()
clf = clf.fit(iris.data, iris.target)


In [68]:
print(np.shape(iris.data))

(150, 4)


In [70]:
iris.data[149, :]

array([5.9, 3. , 5.1, 1.8])

In [61]:
iris.data[5, :]

array([5.4, 3.9, 1.7, 0.4])

In [72]:
clf.predict(iris.data[:10, :]) 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
np.sum(clf.predict(iris.data[:130, :]) ) 

110

In [65]:
# Alternatively, the probability of each class can be predicted, which is the fraction of training samples of the same class in a leaf
clf.predict_proba(iris.data[:1, :])

array([[1., 0., 0.]])

In [73]:
from sklearn.datasets import make_hastie_10_2
from IPython.display import display
import pandas as pd 
x, y = make_hastie_10_2()
df = pd.DataFrame(x)
df['Y'] = y
display(df)

0         1         2         3         4         5         6  \
0     -0.870716 -2.540629 -0.025814 -1.016499 -0.287056  0.229706 -0.924571   
1      0.143591 -1.048010  1.980638  1.199602  0.083958 -1.017653  0.451292   
2     -0.085304  0.353876 -1.754705  1.243128 -0.914868  0.305403 -2.510571   
3     -0.079525 -1.175333  0.178160 -0.074989  1.037825 -1.329029 -0.369398   
4     -0.271138  1.870843 -0.946545  0.906102  0.008632  0.623932 -0.247917   
5     -1.892867  0.255265 -1.957443 -1.564878  0.789182 -0.921502  0.319279   
6     -1.105377 -1.173451  1.108833 -0.685181 -1.392090 -0.780494 -1.084546   
7     -1.768469 -0.115585  1.989001 -0.835394 -0.046989  0.978338  0.947251   
8      1.590165  0.559940  1.282899  0.120685 -0.856146 -0.525670  0.937304   
9      0.118249  0.045123 -0.979277 -0.102409 -0.572871 -0.580442 -2.198135   
10     0.085387  0.823020 -1.242599  1.706867 -0.308785 -0.352421 -2.096432   
11     0.081933 -1.207133 -0.691949  0.059042  0.995750  1.761372  0.090681   
12    -1.301161  1.247218  0.574812  0.832306 -0.666556  1.774307  0.682111   
13     0.353311  0.500582 -0.280482 -0.514886 -0.300380 -0.619996  0.376675   
14    -0.604706 -0.219140 -1.182709 -1.062888  0.024115 -0.050354  0.208363   
15     2.470850  0.196626  1.773588 -0.783472 -0.052601  0.247663 -0.439570   
16    -0.261013 -0.344306  1.537451  1.200087  1.270726 -1.844427  0.211617   
17    -0.894386  0.968009  0.270891  1.797655 -0.931417  1.709680  2.186237   
18    -0.424313  0.538245 -0.601889  0.476688 -1.302991  0.370472  1.046281   
19    -0.920627 -0.769558  1.501984  0.304647  0.280842  0.900650  1.498041   
20    -0.026697  2.275078  0.853021 -0.565617  0.708669 -0.233696  0.427136   
21     0.027672 -0.275102 -1.036988 -0.787192 -0.039535  0.448697  0.840567   
22    -1.232207 -0.320203 -0.513959 -0.508161 -0.289098 -0.316068 -0.132149   
23     0.271914  1.526496  0.558130 -2.107181 -0.469496  1.200627 -0.618710   
24     0.797220  0.686724 -1.336169 -0.773244 -0.107664  0.520114 -1.527998   
25    -0.084965  0.195299 -1.020505 -0.389382 -0.383908  0.473520 -0.266197   
26     1.681650  0.718009 -1.512046  0.439106  0.452512  0.606160 -1.230840   
27     0.622798  0.791423  0.582871  1.619154 -0.201126 -0.613748  1.142791   
28     0.849616  0.307138 -1.030964 -0.038268 -0.503137  0.478983  0.844211   
29    -0.224431  0.241383  0.863331 -0.116174  1.182162  1.813826  1.939107   
...         ...       ...       ...       ...       ...       ...       ...   
11970 -2.699347 -1.041973 -1.437640 -0.275696  0.206838  0.351106 -0.049603   
11971 -0.451867  1.171733  2.059115 -0.365599  0.073542 -1.086215  0.289183   
11972 -1.463453 -1.289804  0.882562 -1.518100 -0.365364 -0.136070 -0.057976   
11973 -1.413778 -0.833697  0.502881 -0.800273  0.803519 -1.276217  0.078571   
11974  1.658893  0.404783 -0.556971 -0.319624 -1.024431  0.188668 -0.667844   
11975  0.140340 -0.194818 -0.121772 -0.778489  0.028727 -0.944090 -0.886098   
11976  0.083322  0.408376  0.979192  0.860776  0.228016 -2.322453  1.127095   
11977  0.783964 -0.319152  1.200353  1.851841  1.102380 -0.665453  0.090798   
11978  0.371910 -1.192175 -0.241088 -1.944559  0.140011  2.078259 -0.128667   
11979  1.545436  0.853629  0.728101  0.563115  0.010577  0.101118 -0.617469   
11980  1.055359  0.776703 -1.291950 -1.253517  1.932467  0.025278 -2.057440   
11981 -1.289730 -1.031642  0.413849 -0.611669 -0.540799 -0.382658 -0.716003   
11982  1.299663 -0.776182 -0.945294  1.468648  0.532669  2.081392  0.365285   
11983 -0.985080  0.609877  1.231454  1.479728 -0.031694  0.034195  0.205822   
11984  1.229907  0.493280 -0.730986 -2.115304 -0.992141 -0.681546  0.885101   
11985  0.957285 -1.206434  0.205874 -0.001398 -1.327694 -1.233435 -0.905596   
11986  0.067491 -0.183651  0.041974  0.588729 -1.613774  0.418198  0.685309   
11987  2.671898 -0.060913 -0.379099 -1.025919  0.045294 -0.924724 -0.196183   
11988  0.931601 -2.460781  0.763035 -0.160287 -0.750053  1.39296

In [74]:
range(10, 410, 10)


range(10, 410, 10)

In [75]:
x_range = range(10, 410, 10)
for i in x_range:
    print(i)

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400


In [76]:
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris
from sklearn.ensemble import AdaBoostClassifier

iris = load_iris()
clf = AdaBoostClassifier(n_estimators=100)
scores = cross_val_score(clf, iris.data, iris.target)
scores.mean()        

0.9599673202614379

In [77]:
np.shape(scores)

(3,)

In [78]:
print(scores)

[0.98039216 0.94117647 0.95833333]
